# Generated by Django 5.2.5 on 2026-01-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardprofile',
            unique_together=set(),
        ),
    ]
