# Generated by Django 5.2.5 on 2025-12-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(blank=True, max_length=64, null=True)),
                ('highlight_word', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('format', models.CharField(choices=[('en ligne', 'En ligne'), ('présentiel', 'Présentiel')], default='présentiel', max_length=20)),
                ('type', models.CharField(choices=[('ordinaire', 'Ordinaire'), ('débat', 'Débat'), ('concours', 'Concours'), ('élections', 'Élections'), ('récréative', 'Récréative')], default='ordinaire', max_length=20)),
                ('attribution_role', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=15)),
                ('location', models.TextField(max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('top_grammar', models.CharField(blank=True, max_length=100, null=True)),
                ('top_amelioration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('video', 'Vidéo'), ('youtube', 'Youtube'), ('pdf', 'PDF'), ('url', 'URL'), ('fichier', 'Fichier')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('min_secondes_duration', models.PositiveIntegerField(default=0)),
                ('max_secondes_duration', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
