# Generated by Django 5.2.5 on 2026-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
