# Generated by Django 5.2.9 on 2026-01-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meeting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressources",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "Sélectionnez un type de ressource"),
                    ("video", "Vidéo"),
                    ("youtube", "Youtube"),
                    ("pdf", "PDF"),
                    ("url", "URL"),
                    ("fichier", "Fichier"),
                ],
                max_length=10,
            ),
        ),
    ]
