# Generated by Django 5.2.5 on 2025-12-25 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='meetings.meeting')),
                ('orator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='meetings.role')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pertinence', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('structure', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('clarte', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('eloquence', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_done', to=settings.AUTH_USER_MODEL)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='speechs.speech')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Meilleur discours', 'Meilleur discours'), ('Meilleure improvisation', 'Meilleure improvisation'), ('Meilleure évaluation', 'Meilleure évaluation'), ('Meilleur français', 'Meilleur français'), ('Meilleure amélioration', 'Meilleure amélioration')], max_length=100)),
                ('issue_date', models.DateField()),
                ('is_won', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='speechs.speech')),
            ],
        ),
    ]
