# Generated by Django 5.2.5 on 2026-01-09 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_meetingattendance'),
        ('members', '0002_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('progression_field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('points', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('grammaire', 'Grammaire'), ('gestion_temps', 'Gestion du temps'), ('improvisation', 'Improvisation'), ('discours_prepare', 'Discours préparé'), ('evaluation_generale', 'Évaluation générale')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('profiles', models.ManyToManyField(to='members.profile')),
                ('criteria', models.ManyToManyField(to='speechs.evaluationcriteria')),
                ('evaluation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechs.evaluationtype')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechs.evaluation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechs.evaluationcriteria')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speechs.evaluationlevel')),
            ],
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='evaluation_types',
            field=models.ManyToManyField(to='speechs.evaluationtype'),
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='meetings.meeting')),
                ('orator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='meetings.role')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Meilleur discours', 'Meilleur discours'), ('Meilleure improvisation', 'Meilleure improvisation'), ('Meilleure évaluation', 'Meilleure évaluation'), ('Meilleur français', 'Meilleur français'), ('Meilleure amélioration', 'Meilleure amélioration')], max_length=100)),
                ('issue_date', models.DateField()),
                ('is_won', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='speechs.speech')),
            ],
        ),
    ]
