# Generated by Django 5.2.5 on 2026-01-09 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='level',
        ),
        migrations.AddField(
            model_name='evaluationanswer',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluationanswer',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='speechs.evaluation'),
        ),
    ]
