# Generated by Django 5.2.5 on 2026-01-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingattendance'),
        ('speechs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='orator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speech',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='meetings.role'),
        ),
    ]
