# Generated by Django 5.2.5 on 2026-01-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechs', '0002_remove_evaluationanswer_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationanswer',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
