# Generated by Django 5.2.5 on 2026-01-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='curriculums',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='statuts',
        ),
        migrations.AddField(
            model_name='profile',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='members.curriculum'),
        ),
        migrations.AddField(
            model_name='profile',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='members.statut'),
        ),
    ]
