# Generated by Django 5.2.5 on 2026-01-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_profile_curriculums_remove_profile_statuts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.ForeignKey(blank=True, default='Membre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='members.statut'),
        ),
    ]
