# Generated by Django 5.2.5 on 2026-01-13 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='members.statut'),
        ),
    ]
