# Generated by Django 5.2.5 on 2026-01-02 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emaillist'),
        ('members', '0002_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emails/attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_mails_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('send_now', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('once', 'Une seule fois'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biWeekly', 'Aux deux semaines'), ('monthly', 'Mensuel')], default='once', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attachments', models.ManyToManyField(blank=True, to='communications.emailattachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL)),
                ('to_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_scheduled', to='communications.emaillist')),
                ('to_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_scheduled', to='members.profile')),
            ],
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_list', to='communications.emailscheduled'),
        ),
    ]
