# Generated by Django 5.2.5 on 2026-01-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_emailattachment_alter_emaillist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailscheduled',
            name='frequency',
            field=models.CharField(choices=[('Une seule fois', 'Une seule fois'), ('Quotidien', 'Quotidien'), ('Hebdomadaire', 'Hebdomadaire'), ('Aux deux semaines', 'Aux deux semaines'), ('Mensuel', 'Mensuel')], default='once', max_length=20),
        ),
    ]
