# Generated by Django 5.2.5 on 2026-01-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_emailscheduled_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MEETING_REMINDER', 'RAPPEL REUNION'), ('ABSENCE_WARNING', 'ABSENCE ALERTE'), ('ROLE_REMINDER', 'RAPPEL ROLE'), ('ROLE_ATTRIBUTION', 'ATTRIBUTION ROLE'), ('CERTIFICAT_ATTRIBUTION', 'ATTRIBUTION CERTIFICAT')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('send_offset', models.CharField(choices=[('M30_BEFORE', '30 minutes avant'), ('M30_AFTER', '30 minutes après'), ('H1_BEFORE', '1 heure avant'), ('H1_AFTER', '1 heure après'), ('H2_BEFORE', '2 heures avant'), ('H2_AFTER', '2 heures après'), ('H4_BEFORE', '4 heures avant'), ('H4_AFTER', '4 heures après'), ('H8_BEFORE', '8 heures avant'), ('H8_AFTER', '8 heures après'), ('H12_BEFORE', '12 heures avant'), ('H12_AFTER', '12 heures après'), ('D1_BEFORE', '1 jour avant'), ('D1_AFTER', '1 jour après'), ('D2_BEFORE', '2 jours avant'), ('D2_AFTER', '2 jours après'), ('D3_BEFORE', '3 jours avant'), ('D3_AFTER', '3 jours après'), ('D5_BEFORE', '5 jours avant'), ('D5_AFTER', '5 jours après'), ('D7_BEFORE', '7 jours avant'), ('D7_AFTER', '7 jours après')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceEmailCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_count', models.PositiveIntegerField(choices=[(1, '1 absence'), (2, '2 absences'), (3, '3 absences')])),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Dernière fois que cet email a été envoyé', null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absence_condition', to='communications.systememail')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='system_emails/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.systememail')),
            ],
        ),
    ]
