# Generated by Django 5.2.5 on 2026-01-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_systememail_absenceemailcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememail',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
