# Generated by Django 5.2.5 on 2026-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_systememail_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systememail',
            name='send_offset',
            field=models.CharField(blank=True, choices=[('M30_BEFORE', '30 minutes avant'), ('M30_AFTER', '30 minutes après'), ('H1_BEFORE', '1 heure avant'), ('H1_AFTER', '1 heure après'), ('H2_BEFORE', '2 heures avant'), ('H2_AFTER', '2 heures après'), ('H4_BEFORE', '4 heures avant'), ('H4_AFTER', '4 heures après'), ('H8_BEFORE', '8 heures avant'), ('H8_AFTER', '8 heures après'), ('H12_BEFORE', '12 heures avant'), ('H12_AFTER', '12 heures après'), ('D1_BEFORE', '1 jour avant'), ('D1_AFTER', '1 jour après'), ('D2_BEFORE', '2 jours avant'), ('D2_AFTER', '2 jours après'), ('D3_BEFORE', '3 jours avant'), ('D3_AFTER', '3 jours après'), ('D5_BEFORE', '5 jours avant'), ('D5_AFTER', '5 jours après'), ('D7_BEFORE', '7 jours avant'), ('D7_AFTER', '7 jours après')], max_length=20, null=True),
        ),
    ]
