# Generated by Django 5.2.5 on 2026-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_systememail_send_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systememail',
            name='code',
            field=models.CharField(choices=[('MEETING_REMINDER', 'RAPPEL REUNION'), ('ABSENCE_WARNING', 'ABSENCE ALERTE'), ('ROLE_REMINDER', 'RAPPEL ROLE'), ('ROLE_ATTRIBUTION', 'ATTRIBUTION ROLE'), ('CERTIFICAT_ATTRIBUTION', 'ATTRIBUTION CERTIFICAT'), ('MEETING_ALERT', 'NOUVELLE REUNION')], max_length=50, unique=True),
        ),
    ]
