# Generated by Django 5.2.5 on 2026-01-08 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_notification_sender'),
        ('meetings', '0002_meetingattendance'),
        ('members', '0002_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systememail',
            name='send_offset',
            field=models.CharField(blank=True, choices=[('M5_BEFORE', '5 minutes avant'), ('M5_AFTER', '5 minutes après'), ('M15_BEFORE', '15 minutes avant'), ('M15_AFTER', '15 minutes après'), ('M30_BEFORE', '30 minutes avant'), ('M30_AFTER', '30 minutes après'), ('H1_BEFORE', '1 heure avant'), ('H1_AFTER', '1 heure après'), ('H2_BEFORE', '2 heures avant'), ('H2_AFTER', '2 heures après'), ('H4_BEFORE', '4 heures avant'), ('H4_AFTER', '4 heures après'), ('H8_BEFORE', '8 heures avant'), ('H8_AFTER', '8 heures après'), ('H12_BEFORE', '12 heures avant'), ('H12_AFTER', '12 heures après'), ('D1_BEFORE', '1 jour avant'), ('D1_AFTER', '1 jour après'), ('D2_BEFORE', '2 jours avant'), ('D2_AFTER', '2 jours après'), ('D3_BEFORE', '3 jours avant'), ('D3_AFTER', '3 jours après'), ('D5_BEFORE', '5 jours avant'), ('D5_AFTER', '5 jours après'), ('D7_BEFORE', '7 jours avant'), ('D7_AFTER', '7 jours après')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SystemEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.systememail')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
            options={
                'unique_together': {('email_config', 'recipient', 'meeting')},
            },
        ),
    ]
