# Generated by Django 5.2.5 on 2026-01-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_alter_notification_sender_and_more'),
        ('members', '0005_alter_profile_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailscheduled',
            name='to_email',
        ),
        migrations.RemoveField(
            model_name='emailscheduled',
            name='to_list',
        ),
        migrations.RemoveField(
            model_name='emailscheduled',
            name='to_profile',
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='to_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='to_lists',
            field=models.ManyToManyField(blank=True, related_name='emails_scheduled', to='communications.emaillist'),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='to_profiles',
            field=models.ManyToManyField(blank=True, related_name='emails_scheduled', to='members.profile'),
        ),
        migrations.AlterField(
            model_name='emailscheduled',
            name='frequency',
            field=models.CharField(choices=[('once', 'Une seule fois'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Aux deux semaines'), ('monthly', 'Mensuel')], default='once', max_length=20),
        ),
    ]
