# Generated by Django 5.2.5 on 2026-01-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0011_remove_emailscheduled_to_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
